---
- name: Hello Message
  debug:
    msg: "Hello World Katalon_Job Role!"

- name: Get Cluster Info
  command: kubectl cluster-info
  register: kubectllog

- name: Render Katalon Job Template
  set_fact:
    "{{ item }}": "{{ lookup('template', item + '.yml.j2') }}"
  with_items:
    - "config"
    - "job"
  no_log: true

- name: Create Katalon Config Job Template
  copy:
    content: "{{config }}"
    dest: /home/coe/jobs/ansible-config.yaml

- name: Create Katalon Config Job Template
  copy:
    content: "{{job }}"
    dest: /home/coe/jobs/ansible-job.yaml

- name: Apply Katalon Job
  command: |
    echo {{ item | quote }} | {{ kubectl }} apply -f -
  with_items:
    - "{{ config }}"
    - "{{ job }}"
  no_log: false

- name: Get Katalon Job Information
  shell: kubectl describe pods
  no_log: false
