---
- name: Create Katalon Config Job Template
  copy:
    content: "{{ config }}"
    dest: /home/coe/jobs/ansible-config.yaml

- name: Create Katalon Config Job Template
  copy:
    content: "{{ job }}"
    dest: /home/coe/jobs/ansible-job.yaml

- name: Apply Katalon Job
  shell: |
    echo {{ item | quote }} | {{ kubectl_cmd }} apply -f -
  with_items:
    - "{{ config }}"
    - "{{ job }}"
  no_log: false

- name: Get Katalon Job Information
  shell: kubectl describe pods -n {{ kubernetes_namespace }} | sed -n '/^Containers/,/Conditions/p' | grep Reason | awk '{split($0,a," "); print a[2]}'
  register: pod_state
  until: pod_state.stdout == "Completed"
  retries: 3
  delay: 60
  no_log: false

- name: DEBUG
  debug:
    msg: Pod status is {{ pod_state.stdout }}

- name: Get logs
  shell: kubectl logs job/katalonstudio -n {{ kubernetes_namespace }} | sed -n '/<?xml/,/testsuites>/p' >> junit.xml

- name: Delete job & pod
  shell: kubectl delete job -l name={{ job_name }} -n {{ kubernetes_namespace }}
