---
- name: Hello Message
  debug:
    msg: "Hello World Katalon_Job Role!"
- name: Get Cluster Info
  command: kubectl cluster-info
  register: kubectl
- name: Print Check Info
  debug:
    var: kubectl
    verbosity: 3
- name: Render Katalon Job Template
  set_fact:
    "{{ item }}": "{{ lookup('template', item + '.yml.j2') }}"
  with_items:
    - "config"
    - "job"
  no_log: false
- name: Apply Katalon Job
  shell: |
    echo {{ item | quote }} | {{ kubectl }} apply -f -
  with_items:
    - "{{ config }}"
    - "{{ job }}"
  no_log: false

- name: Get Katalon Job Information
  shell: kubectl describe pods
  no_log: false
