---
- name: Create Katalon Config Job Template
  copy:
    content: "{{ config }}"
    dest: /home/coe/jobs/ansible-config.yaml

- name: Create Katalon Config Job Template
  copy:
    content: "{{ job }}"
    dest: /home/coe/jobs/ansible-job.yaml

- name: Apply Katalon Job
  shell: |
    echo {{ item | quote }} | {{ kubectl_cmd }} apply -f -
  with_items:
    - "{{ config }}"
    - "{{ job }}"
  no_log: false

- name: Get Katalon Job Information
  shell: kubectl describe pods -n {{ kubernetes_namespace }} | sed -n '/^Containers/,/Conditions/p' | grep Reason | awk '{split($0,a," "); print a[2]}'
  register: pod_state
  until: pod_state.stdout == "Completed"
  retries: 3
  delay: 60
  no_log: false

- name: Get logs to file
  shell: kubectl logs job/katalonstudio -n {{ kubernetes_namespace }} | sed -n '/<?xml/,/testsuites>/p' > junit.xml

- name: Extract stack trace for notification: Root cause + 9 lines below
  shell: |
      firstline=$(kubectl logs job/katalonstudio -n {{ kubernetes_namespace }} | grep -n '\[TEST_STEP\]\[FAILED\]' | cut -d : -f1)
      kubectl logs job/katalonstudio -n {{ kubernetes_namespace  }} | sed -n $firstline,$(($firstline+9))p
  register: stack_trace

- name: Write stack trace to file
  copy:
      content: "{{ stack_trace.stdout }}"
      dest: /tmp/stack_trace.txt
      follow: yes

- name: Delete job & pod
  shell: kubectl delete job -l name={{ job_name }} -n {{ kubernetes_namespace }}
