- name: Create issue
  jira:
    uri: '{{ server }}'
    username: '{{ jira_user }}'
    password: '{{ jira_pass }}'
    project: VOX
    operation: create
    summary: '{{ issue_summary }}'
    description: '{{ issue_description }}'
    issuetype: Bug
  register: issue

