---
- name: Main Job Here
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Set kubectl variable command
      set_fact:
        kubectl_cmd: "{{ 'kubectl' }}"
        cacheable: yes
    - name: Render Katalon Job Template
      set_fact:
        "{{ item }}": "{{ lookup('template', 'roles/katalon_jobs/templates/' item + '.yml.j2') }}"
      with_items:
        - "config"
        - "job"
      no_log: false
  roles:
    - katalon_job
