---
- name: Main Job Here
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Use kubectl
      set_fact:
        kubectl_cmd: "{{ 'kubectl' }}"
        cacheable: yes
  roles:
    - debug
    - katalon_job
